export const KEYBOARD = [
  { label: "clear", className: "clear", type: "clear" },
  { label: "del", className: "del", type: "del" },
  { label: "+", className: "plus", type: "operator" },
  { label: "-", className: "minus", type: "operator" },
  { label: "/", className: "divide", type: "operator" },
  { label: "*", className: "multiple", type: "operator" },
  { label: "=", className: "equal", type: "equal" },
  { label: "0", className: "zero", type: "number" },
  { label: "1", className: "one", type: "number" },
  { label: "2", className: "two", type: "number" },
  { label: "3", className: "three", type: "number" },
  { label: "4", className: "four", type: "number" },
  { label: "5", className: "five", type: "number" },
  { label: "6", className: "six", type: "number" },
  { label: "7", className: "seven", type: "number" },
  { label: "8", className: "eight", type: "number" },
  { label: "9", className: "nine", type: "number" },
];
